"""Generate the frontend's layer manifest from the registry — the TS half.

`render_ts()` emits ``frontend/src/lib/layers.gen.ts`` from REGISTRY: the `LayerId`
union, the default visibility, the `LayerPanel` sections, and the `useData` fetch
manifest. This is the "TS generated from the Python registry" the vision calls for
(§4): adding a layer is one descriptor here, and the TS id-set / panel / defaults
follow. ``test_registry_codegen.py`` fails CI if the committed file drifts from this.

Run:  cd backend && uv run python -m freight_radar.registry.codegen
"""

from __future__ import annotations

from pathlib import Path

from .layers import REGISTRY, Producer, globe_descriptors

# Section-level copy (the only per-section metadata that isn't per-layer). The
# Context caption is part of the honesty rail — kept here so it stays registry-driven.
_SECTION_ORDER = ("Freight", "Context")
_SECTION_CAPTION = {
    "Freight": None,
    "Context": "possibly-related context, not a stated cause",
}

_OUT = Path(__file__).resolve().parents[3] / "frontend" / "src" / "lib" / "layers.gen.ts"

_HEADER = """/* eslint-disable */
// GENERATED by backend/freight_radar/registry/codegen.py — DO NOT EDIT BY HAND.
// Source of truth: backend/freight_radar/registry/layers.py (the LayerDescriptor
// registry). Regenerate:  cd backend && uv run python -m freight_radar.registry.codegen
// A backend test (test_registry_codegen.py) fails CI if this drifts from the registry.
"""


def _q(s: str) -> str:
    return f"'{s}'"


def render_ts() -> str:
    globe = globe_descriptors()  # ordered by (section, order)
    ids = [d.globe.layer_id for d in globe]  # type: ignore[union-attr]

    lines: list[str] = [_HEADER, ""]

    # ---- LayerId union + LayerVisibility ----
    lines.append("// The toggleable globe overlays (LayerPanel + the buildLayers visibility gate).")
    lines.append("export type LayerId =")
    for i, lid in enumerate(ids):
        tail = ";" if i == len(ids) - 1 else ""
        lines.append(f"  | {_q(lid)}{tail}")
    lines.append("")
    lines.append("export type LayerVisibility = Record<LayerId, boolean>;")
    lines.append("")

    # ---- LAYER_IDS ----
    lines.append("export const LAYER_IDS: readonly LayerId[] = [")
    for lid in ids:
        lines.append(f"  {_q(lid)},")
    lines.append("];")
    lines.append("")

    # ---- DEFAULT_LAYER_VISIBILITY ----
    lines.append("// First-paint defaults (App.tsx seeds layer state from this, then localStorage).")
    lines.append("export const DEFAULT_LAYER_VISIBILITY: LayerVisibility = {")
    for d in globe:
        val = "true" if d.globe.default_on else "false"  # type: ignore[union-attr]
        lines.append(f"  {d.globe.layer_id}: {val},")  # type: ignore[union-attr]
    lines.append("};")
    lines.append("")

    # ---- LAYER_SECTIONS (the LayerPanel grouping) ----
    lines.append("export interface LayerRow {")
    lines.append("  id: LayerId;")
    lines.append("  label: string;")
    lines.append("  sw: string;")
    lines.append("}")
    lines.append("export interface LayerSection {")
    lines.append("  title: string;")
    lines.append("  caption?: string;")
    lines.append("  rows: LayerRow[];")
    lines.append("}")
    lines.append("")
    lines.append("// Freight = the measured spine; Context = cited public data, never a stated cause.")
    lines.append("export const LAYER_SECTIONS: LayerSection[] = [")
    for section in _SECTION_ORDER:
        rows = [d for d in globe if d.globe.section == section]  # type: ignore[union-attr]
        if not rows:
            continue
        caption = _SECTION_CAPTION.get(section)
        lines.append("  {")
        lines.append(f"    title: {_q(section)},")
        if caption:
            lines.append(f"    caption: {_q(caption)},")
        lines.append("    rows: [")
        for d in rows:
            g = d.globe  # type: ignore[union-attr]
            lines.append(
                f"      {{ id: {_q(g.layer_id)}, label: {_q(g.label)}, sw: {_q(g.swatch)} }},"
            )
        lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    lines.append("")

    # ---- the useData fetch manifest ----
    core = [d for d in REGISTRY if d.producer is Producer.CORE and d.fetch_file]
    optional = [
        d for d in REGISTRY if d.fetch_file and d.producer is not Producer.CORE
    ]
    lines.append("// The data files useData() loads. CORE is required (the app blocks on it);")
    lines.append("// OPTIONAL degrades to null when absent. test_registry_codegen asserts useData")
    lines.append("// fetches exactly this set — the registry stays the single source of truth.")
    lines.append("export const CORE_FILES: readonly string[] = [")
    for d in core:
        lines.append(f"  {_q(d.fetch_file)},")  # type: ignore[arg-type]
    lines.append("];")
    lines.append("export const OPTIONAL_SIDECAR_FILES: readonly string[] = [")
    for d in optional:
        lines.append(f"  {_q(d.fetch_file)},")  # type: ignore[arg-type]
    lines.append("];")
    lines.append("")

    return "\n".join(lines)


def write() -> Path:
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(render_ts())
    return _OUT


if __name__ == "__main__":
    p = write()
    print(f"wrote {p} ({p.stat().st_size:,} bytes)")
