// GENERATED by backend/freight_radar/registry/codegen.py — DO NOT EDIT BY HAND.
// Source of truth: backend/freight_radar/registry/shapes.py (the shape registry the data
// contracts also derive from). types.ts RE-EXPORTS these, so every `from '../types'` import
// keeps working. Only mechanical, comment-free CONTEXT shapes are generated here; the spine /
// signals / UI shapes stay hand-authored in types.ts. Regenerate:
//   cd backend && uv run python -m freight_radar.registry.codegen
// A backend test (test_registry_codegen.py) fails CI if this drifts from the shapes.

// ---- quakes.json (derived from registry/shapes.py) ----
export interface QuakeItem {
  id: string;
  mag: number;
  place: string;
  lat: number;
  lon: number;
  depth_km: number | null;
  time: string;
  tsunami: boolean;
  url: string;
}
export interface Quakes {
  generated_at: string;
  as_of: string;
  source: string;
  source_url: string;
  disclaimer: string;
  min_mag: number;
  counts: { total: number; m5plus: number };
  items: QuakeItem[];
}

// ---- eonet.json (derived from registry/shapes.py) ----
export interface EonetItem {
  id: string;
  title: string;
  category: string;
  lat: number;
  lon: number;
  date: string;
  url: string;
}
export interface Eonet {
  generated_at: string;
  as_of: string;
  source: string;
  source_url: string;
  disclaimer: string;
  counts: { events: number; by_category: Record<string, number> };
  items: EonetItem[];
}

// ---- marine.json (derived from registry/shapes.py) ----
export interface MarineItem {
  name: string;
  lat: number;
  lon: number;
  wave_height_m: number;
  wave_period_s: number | null;
  observed_at: string;
}
export interface Marine {
  generated_at: string;
  as_of: string;
  source: string;
  source_url: string;
  disclaimer: string;
  counts: { chokepoints: number };
  items: MarineItem[];
}

// ---- tides.json (derived from registry/shapes.py) ----
export interface TideItem {
  port: string;
  station: string;
  lat: number;
  lon: number;
  water_level_ft: number;
  observed_at: string;
  url: string;
}
export interface Tides {
  generated_at: string;
  as_of: string;
  source: string;
  source_url: string;
  disclaimer: string;
  counts: { ports: number };
  items: TideItem[];
}

// ---- streamflow.json (derived from registry/shapes.py) ----
export interface StreamflowItem {
  site: string;
  river: string;
  place: string;
  lat: number;
  lon: number;
  stage_ft: number;
  observed_at: string;
  url: string;
}
export interface Streamflow {
  generated_at: string;
  as_of: string;
  source: string;
  source_url: string;
  disclaimer: string;
  counts: { gauges: number };
  items: StreamflowItem[];
}

// ---- disruptions.json (derived from registry/shapes.py) ----
export interface DisruptionEvent {
  eventid: number;
  type: string;
  type_label: string;
  name: string;
  alertlevel: string;
  country: string;
  from: string;
  to: string;
  lat: number;
  lon: number;
  severity: string;
  affected_ports: { portid: string; name: string }[];
  n_affected_ports: number;
  near_chokepoints: { portid: string; name: string; km: number }[];
  affected_population: string;
}
export interface Disruptions {
  generated_at: string;
  as_of: string;
  window_days: number;
  source: string;
  source_url: string;
  events: DisruptionEvent[];
  counts: { events: number; red: number; flags_corroborated: number };
}

// ---- gatun.json (derived from registry/shapes.py) ----
export interface GatunProjection {
  date: string;
  level_ft: number;
  surcharge_pct: number;
  neopanamax_draft_ft: number;
  panamax_draft_ft: number;
}
export interface Gatun {
  available: boolean;
  portid: string;
  name: string;
  as_of: string;
  current_level_ft: number;
  pctile_alltime: number;
  change_30d_ft: number;
  change_365d_ft: number;
  level_spark: number[];
  normal_max_draft_ft: number;
  min_projected_neopanamax_draft_ft: number;
  draft_restricted: boolean;
  surcharge_pct_now: number;
  projection: GatunProjection[];
  source: string;
  source_url: string;
  disclaimer: string;
  lat: number;
  lon: number;
  generated_at: string;
}
