/* eslint-disable */
// GENERATED by backend/freight_radar/registry/codegen.py — DO NOT EDIT BY HAND.
// Source of truth: backend/freight_radar/registry/layers.py (the LayerDescriptor
// registry). Regenerate:  cd backend && uv run python -m freight_radar.registry.codegen
// A backend test (test_registry_codegen.py) fails CI if this drifts from the registry.


// The toggleable globe overlays (LayerPanel + the buildLayers visibility gate).
export type LayerId =
  | 'flags'
  | 'chokepoints'
  | 'ports'
  | 'ships'
  | 'lanes'
  | 'news'
  | 'quakes'
  | 'storms'
  | 'wind'
  | 'satellite'
  | 'eonet'
  | 'marine'
  | 'tides'
  | 'streamflow'
  | 'hazards';

export type LayerVisibility = Record<LayerId, boolean>;

export const LAYER_IDS: readonly LayerId[] = [
  'flags',
  'chokepoints',
  'ports',
  'ships',
  'lanes',
  'news',
  'quakes',
  'storms',
  'wind',
  'satellite',
  'eonet',
  'marine',
  'tides',
  'streamflow',
  'hazards',
];

// First-paint defaults (App.tsx seeds layer state from this, then localStorage).
export const DEFAULT_LAYER_VISIBILITY: LayerVisibility = {
  flags: true,
  chokepoints: true,
  ports: true,
  ships: true,
  lanes: true,
  news: true,
  quakes: false,
  storms: true,
  wind: true,
  satellite: false,
  eonet: false,
  marine: false,
  tides: false,
  streamflow: false,
  hazards: false,
};

export interface LayerRow {
  id: LayerId;
  label: string;
  sw: string;
}
export interface LayerSection {
  title: string;
  caption?: string;
  rows: LayerRow[];
}

// Freight = the measured spine; Context = cited public data, never a stated cause.
export const LAYER_SECTIONS: LayerSection[] = [
  {
    title: 'Freight',
    rows: [
      { id: 'flags', label: 'flagged', sw: 'pulse' },
      { id: 'chokepoints', label: 'chokepoints', sw: 'amber' },
      { id: 'ports', label: 'ports', sw: 'port' },
      { id: 'ships', label: 'vessels', sw: 'ship' },
      { id: 'lanes', label: 'lanes', sw: 'lane' },
    ],
  },
  {
    title: 'Context',
    caption: 'possibly-related context, not a stated cause',
    rows: [
      { id: 'news', label: 'news', sw: 'news' },
      { id: 'quakes', label: 'earthquakes', sw: 'quake' },
      { id: 'storms', label: 'storms', sw: 'storm' },
      { id: 'wind', label: 'wind', sw: 'wind' },
      { id: 'satellite', label: 'satellite', sw: 'sat' },
      { id: 'eonet', label: 'events', sw: 'event' },
      { id: 'marine', label: 'seas', sw: 'wave' },
      { id: 'tides', label: 'tides', sw: 'tide' },
      { id: 'streamflow', label: 'rivers', sw: 'river' },
      { id: 'hazards', label: 'hazards', sw: 'hazard' },
    ],
  },
];

// The data files useData() loads. CORE is required (the app blocks on it);
// OPTIONAL degrades to null when absent. test_registry_codegen asserts useData
// fetches exactly this set — the registry stays the single source of truth.
export const CORE_FILES: readonly string[] = [
  'data/snapshot.json',
  'data/flags.json',
  'data/lanes.json',
];
export const OPTIONAL_SIDECAR_FILES: readonly string[] = [
  'data/exposure.json',
  'data/news.json',
  'data/disruptions.json',
  'data/weather.json',
  'data/gatun.json',
  'data/news_geo.json',
  'data/quakes.json',
  'data/timeseries.json',
  'data/market.json',
  'data/stress.json',
  'data/world.json',
  'data/events.json',
  'data/brief.json',
  'data/streamflow.json',
  'data/eonet.json',
  'data/marine.json',
  'data/signals_fdr.json',
  'data/tides.json',
  'data/ships.json',
  'data/wind.json',
];

// Maps each fetched data file to the AppData field it populates. useData()
// iterates CORE_FILES + OPTIONAL_SIDECAR_FILES and assembles AppData through
// this map, so the registry — not a hand-kept fetch list — drives the loader.
export const APPDATA_KEY_MAP: Readonly<Record<string, string>> = {
  'data/snapshot.json': 'snapshot',
  'data/flags.json': 'flags',
  'data/lanes.json': 'lanes',
  'data/exposure.json': 'exposure',
  'data/news.json': 'news',
  'data/disruptions.json': 'disruptions',
  'data/weather.json': 'weather',
  'data/gatun.json': 'gatun',
  'data/news_geo.json': 'newsGeo',
  'data/quakes.json': 'quakes',
  'data/timeseries.json': 'timeseries',
  'data/market.json': 'market',
  'data/stress.json': 'stress',
  'data/world.json': 'world',
  'data/events.json': 'events',
  'data/brief.json': 'brief',
  'data/streamflow.json': 'streamflow',
  'data/eonet.json': 'eonet',
  'data/marine.json': 'marine',
  'data/signals_fdr.json': 'signals',
  'data/tides.json': 'tides',
  'data/ships.json': 'ships',
  'data/wind.json': 'wind',
};
